---
sudo: required
language: python

install:
  - pip install "ome-ansible-molecule<0.5"
  - pip install jmespath

script:
  # Workaround frequent travis timeouts by installing roles ourselves
  # and setting ANSIBLE_ROLES_PATH in molecule.yml
  - travis_retry ansible-galaxy install -r requirements.yml
  - molecule test -s $SCENARIO

env:
  - SCENARIO=bootstrap
  - SCENARIO=jupyterhub
  - SCENARIO=k8s-postgres
  - SCENARIO=nightshade-webclients
  - SCENARIO=ome-demoserver
  - SCENARIO=ome-dundeeomero
  - SCENARIO=omero-training-server
  - SCENARIO=release
  - SCENARIO=web-proxy
  - SCENARIO=www
